// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgBYvyY2YfnpRilWC4AhBhHpVuGjhODo',
    appId: '1:1046853830353:web:488da1cf583bb4e5e9a7f0',
    messagingSenderId: '1046853830353',
    projectId: 'padrao-210e0',
    authDomain: 'padrao-210e0.firebaseapp.com',
    storageBucket: 'padrao-210e0.firebasestorage.app',
    measurementId: 'G-386S0Q9Z8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcDRQab3BY4e_HsfPlk2XHlZ_eQHUQSCY',
    appId: '1:1046853830353:android:e0930dd2591d2935e9a7f0',
    messagingSenderId: '1046853830353',
    projectId: 'padrao-210e0',
    storageBucket: 'padrao-210e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFHGePQe0p0U9mPLNeY_3WmIVaZym-va4',
    appId: '1:1046853830353:ios:cc737c16553a2e85e9a7f0',
    messagingSenderId: '1046853830353',
    projectId: 'padrao-210e0',
    storageBucket: 'padrao-210e0.firebasestorage.app',
    iosBundleId: 'com.example.projetoPadrao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFHGePQe0p0U9mPLNeY_3WmIVaZym-va4',
    appId: '1:1046853830353:ios:cc737c16553a2e85e9a7f0',
    messagingSenderId: '1046853830353',
    projectId: 'padrao-210e0',
    storageBucket: 'padrao-210e0.firebasestorage.app',
    iosBundleId: 'com.example.projetoPadrao',
  );

}